import type {
  AdministratorMember,
  CoachMember,
  MemberOverviewRow,
  MemberSanction,
  MembersState,
  PlayerMember,
  RefereeMember,
} from '../types';

const PLAYER_SANCTIONS: MemberSanction[] = [
  {
    id: 's-warning-1',
    kind: 'warning',
    titleKey: 'members.sanctions.lateArrival.title',
    reasonKey: 'members.sanctions.lateArrival.reason',
    relativeKey: 'members.relative.minutesAgo',
    relativeCount: 14,
  },
  {
    id: 's-suspension-1',
    kind: 'suspension',
    titleKey: 'members.sanctions.fairPlay.title',
    reasonKey: 'members.sanctions.fairPlay.reason',
    relativeKey: 'members.relative.hourAgo',
    relativeCount: 1,
  },
];

function playerOverview(nameKey: string, extras?: Partial<Record<string, string>>): MemberOverviewRow[] {
  return [
    { labelKey: 'members.fields.name', valueKey: nameKey, icon: 'userCard' },
    {
      labelKey: 'members.fields.club',
      valueKey: extras?.clubKey ?? 'members.clubs.jeddahUnion',
      icon: 'club',
    },
    {
      labelKey: 'members.fields.weaponType',
      valueKey: extras?.weaponKey ?? 'members.weapons.foil',
      icon: 'fencing',
    },
    {
      labelKey: 'members.fields.gender',
      valueKey: extras?.genderKey ?? 'create.options.gender.male',
      icon: 'gender',
    },
    {
      labelKey: 'members.fields.ranking',
      value: extras?.ranking ?? '22',
      icon: 'ranking',
      emphasize: true,
    },
    {
      labelKey: 'members.fields.category',
      valueKey: extras?.categoryKey ?? 'create.options.ageCategory.u21',
      icon: 'category',
    },
    {
      labelKey: 'members.fields.nationalTeam',
      valueKey: extras?.nationalTeamKey ?? 'create.options.nationalTeam.calledUp',
      icon: 'usersGroup',
    },
    {
      labelKey: 'members.fields.nationality',
      valueKey: extras?.nationalityKey ?? 'create.options.nationality.saudi',
      icon: 'globe',
    },
    {
      labelKey: 'members.fields.contractEnd',
      valueKey: extras?.contractEndKey ?? 'members.values.contractEnd',
      icon: 'calendar',
    },
    {
      labelKey: 'members.fields.rating',
      value: extras?.rating ?? '1546',
      icon: 'star',
    },
  ];
}

const PLAYERS: PlayerMember[] = [
  {
    id: 'player-abdullah',
    category: 'player',
    nameKey: 'competitions.people.abdullahFaisal',
    photoIndex: 1,
    federationId: 'SFF-A-XCFR7ZBW',
    status: 'active',
    nationalTeam: true,
    chips: [
      { labelKey: 'members.chips.weapon', valueKey: 'members.weapons.epee' },
      { labelKey: 'members.chips.rating', value: '1264' },
      { labelKey: 'members.chips.level', value: '+6', emphasize: true },
    ],
    overview: playerOverview('competitions.people.abdullahFaisal', {
      weaponKey: 'members.weapons.foil',
      rating: '1546',
    }),
    sanctions: PLAYER_SANCTIONS,
  },
  {
    id: 'player-hana',
    category: 'player',
    nameKey: 'competitions.people.hanaRashed',
    photoIndex: 2,
    federationId: 'SFF-A-HANA8K2M',
    status: 'suspended',
    nationalTeam: false,
    chips: [
      { labelKey: 'members.chips.weapon', valueKey: 'members.weapons.foilShort' },
      { labelKey: 'members.chips.rating', value: '1365' },
      { labelKey: 'members.chips.level', value: '+4', emphasize: true },
    ],
    overview: playerOverview('competitions.people.hanaRashed', {
      genderKey: 'create.options.gender.female',
      nationalTeamKey: 'create.options.nationalTeam.notCalledUp',
      ranking: '31',
      rating: '1365',
    }),
    sanctions: PLAYER_SANCTIONS,
  },
  {
    id: 'player-faisal-1',
    category: 'player',
    nameKey: 'competitions.people.faisalQahtani',
    photoIndex: 3,
    federationId: 'SFF-A-FAIS3N1Q',
    status: 'active',
    nationalTeam: false,
    chips: [
      { labelKey: 'members.chips.weapon', valueKey: 'members.weapons.foilShort' },
      { labelKey: 'members.chips.rating', value: '1684' },
      { labelKey: 'members.chips.level', value: '+3', emphasize: true },
    ],
    overview: playerOverview('competitions.people.faisalQahtani', {
      nationalTeamKey: 'create.options.nationalTeam.notCalledUp',
      ranking: '18',
      rating: '1684',
    }),
    sanctions: [],
  },
  {
    id: 'player-faisal-2',
    category: 'player',
    nameKey: 'competitions.people.faisalQahtani',
    photoIndex: 4,
    federationId: 'SFF-A-FAIS4P2R',
    status: 'active',
    nationalTeam: false,
    chips: [
      { labelKey: 'members.chips.weapon', valueKey: 'members.weapons.foilShort' },
      { labelKey: 'members.chips.rating', value: '1684' },
      { labelKey: 'members.chips.level', value: '+3', emphasize: true },
    ],
    overview: playerOverview('competitions.people.faisalQahtani', {
      nationalTeamKey: 'create.options.nationalTeam.notCalledUp',
      ranking: '19',
      rating: '1684',
    }),
    sanctions: [],
  },
  {
    id: 'player-faisal-3',
    category: 'player',
    nameKey: 'competitions.people.faisalQahtani',
    photoIndex: 5,
    federationId: 'SFF-A-FAIS5Q3S',
    status: 'suspended',
    nationalTeam: false,
    chips: [
      { labelKey: 'members.chips.weapon', valueKey: 'members.weapons.foilShort' },
      { labelKey: 'members.chips.rating', value: '1684' },
      { labelKey: 'members.chips.level', value: '+3', emphasize: true },
    ],
    overview: playerOverview('competitions.people.faisalQahtani', {
      nationalTeamKey: 'create.options.nationalTeam.notCalledUp',
      ranking: '27',
      rating: '1684',
    }),
    sanctions: PLAYER_SANCTIONS,
  },
  {
    id: 'player-faisal-4',
    category: 'player',
    nameKey: 'competitions.people.faisalQahtani',
    photoIndex: 6,
    federationId: 'SFF-A-FAIS6R4T',
    status: 'active',
    nationalTeam: false,
    chips: [
      { labelKey: 'members.chips.weapon', valueKey: 'members.weapons.foilShort' },
      { labelKey: 'members.chips.rating', value: '1684' },
      { labelKey: 'members.chips.level', value: '+3', emphasize: true },
    ],
    overview: playerOverview('competitions.people.faisalQahtani', {
      nationalTeamKey: 'create.options.nationalTeam.notCalledUp',
      ranking: '20',
      rating: '1684',
    }),
    sanctions: [],
  },
];

function coachOverview(nameKey: string): MemberOverviewRow[] {
  return [
    { labelKey: 'members.fields.name', valueKey: nameKey, icon: 'userCard' },
    { labelKey: 'members.fields.club', valueKey: 'members.clubs.jeddahUnion', icon: 'club' },
    { labelKey: 'members.fields.role', valueKey: 'create.options.coachRole.headCoach', icon: 'bag' },
    {
      labelKey: 'members.fields.level',
      valueKey: 'create.options.coachLevel.l1',
      icon: 'star',
      emphasize: true,
    },
    { labelKey: 'members.fields.weaponType', valueKey: 'members.weapons.foil', icon: 'fencing' },
    { labelKey: 'members.fields.championships', value: '12', icon: 'cup' },
    { labelKey: 'members.fields.matches', value: '150', icon: 'compare' },
  ];
}

const COACHES: CoachMember[] = [
  {
    id: 'coach-ibrahim-1',
    category: 'coach',
    nameKey: 'members.people.ibrahimSayed',
    photoIndex: 1,
    federationId: 'SFF-C-IBRA1A2B',
    status: 'active',
    chips: [
      { labelKey: 'members.chips.championships', value: '12' },
      { labelKey: 'members.chips.weapon', valueKey: 'members.weapons.sabre' },
      { labelKey: 'members.chips.level', value: '3p', emphasize: true },
      { labelKey: 'members.chips.matches', value: '187' },
    ],
    overview: coachOverview('members.people.ibrahimSayed'),
    sanctions: [],
  },
  {
    id: 'coach-ibrahim-2',
    category: 'coach',
    nameKey: 'members.people.ibrahimSayed',
    photoIndex: 2,
    federationId: 'SFF-C-IBRA2B3C',
    status: 'suspended',
    chips: [
      { labelKey: 'members.chips.championships', value: '12' },
      { labelKey: 'members.chips.weapon', valueKey: 'members.weapons.sabre' },
      { labelKey: 'members.chips.level', value: '3p', emphasize: true },
      { labelKey: 'members.chips.matches', value: '187' },
    ],
    overview: coachOverview('members.people.ibrahimSayed'),
    sanctions: [],
  },
  {
    id: 'coach-ibrahim-3',
    category: 'coach',
    nameKey: 'members.people.ibrahimSayed',
    photoIndex: 3,
    federationId: 'SFF-C-IBRA3C4D',
    status: 'active',
    chips: [
      { labelKey: 'members.chips.championships', value: '12' },
      { labelKey: 'members.chips.weapon', valueKey: 'members.weapons.sabre' },
      { labelKey: 'members.chips.level', value: '3p', emphasize: true },
      { labelKey: 'members.chips.matches', value: '187' },
    ],
    overview: coachOverview('members.people.ibrahimSayed'),
    sanctions: [],
  },
  {
    id: 'coach-ibrahim-4',
    category: 'coach',
    nameKey: 'members.people.ibrahimSayed',
    photoIndex: 4,
    federationId: 'SFF-C-IBRA4D5E',
    status: 'active',
    chips: [
      { labelKey: 'members.chips.championships', value: '12' },
      { labelKey: 'members.chips.weapon', valueKey: 'members.weapons.sabre' },
      { labelKey: 'members.chips.level', value: '3p', emphasize: true },
      { labelKey: 'members.chips.matches', value: '187' },
    ],
    overview: coachOverview('members.people.ibrahimSayed'),
    sanctions: [],
  },
];

function refereeOverview(
  nameKey: string,
  categoryKey: string,
  weaponKey: string,
  entityKey: string,
): MemberOverviewRow[] {
  return [
    { labelKey: 'members.fields.name', valueKey: nameKey, icon: 'userCard' },
    { labelKey: 'members.fields.category', valueKey: categoryKey, icon: 'star', emphasize: true },
    { labelKey: 'members.fields.weaponType', valueKey: weaponKey, icon: 'fencing' },
    { labelKey: 'members.fields.entity', valueKey: entityKey, icon: 'bag' },
    { labelKey: 'members.fields.region', valueKey: 'create.options.region.riyadh', icon: 'club' },
    { labelKey: 'members.fields.certificate', valueKey: 'members.values.fieCertificate', icon: 'cup' },
    { labelKey: 'members.fields.managedEvents', value: '24', icon: 'compare' },
  ];
}

const REFEREES: RefereeMember[] = [
  {
    id: 'referee-salem-1',
    category: 'referee',
    nameKey: 'members.people.salemGhamdi',
    photoIndex: 1,
    federationId: 'SFF-R-SALM1A2B',
    status: 'active',
    chips: [
      { labelKey: 'members.chips.weapon', valueKey: 'members.weapons.all' },
      { labelKey: 'members.chips.events', value: '24' },
      { labelKey: 'members.chips.category', valueKey: 'create.options.refereeCategory.a' },
      { labelKey: 'members.chips.entity', valueKey: 'create.options.entity.civilian' },
    ],
    overview: refereeOverview(
      'members.people.salemGhamdi',
      'members.values.categoryA',
      'members.weapons.allWeapons',
      'create.options.entity.civilian',
    ),
    sanctions: [],
  },
  {
    id: 'referee-salem-2',
    category: 'referee',
    nameKey: 'members.people.salemGhamdi',
    photoIndex: 2,
    federationId: 'SFF-R-SALM2B3C',
    status: 'active',
    chips: [
      { labelKey: 'members.chips.weapon', valueKey: 'members.weapons.sabre' },
      { labelKey: 'members.chips.events', value: '24' },
      { labelKey: 'members.chips.category', valueKey: 'create.options.refereeCategory.b' },
      { labelKey: 'members.chips.entity', valueKey: 'create.options.entity.military' },
    ],
    overview: refereeOverview(
      'members.people.salemGhamdi',
      'members.values.categoryB',
      'members.weapons.sabre',
      'create.options.entity.military',
    ),
    sanctions: [],
  },
  {
    id: 'referee-salem-3',
    category: 'referee',
    nameKey: 'members.people.salemGhamdi',
    photoIndex: 3,
    federationId: 'SFF-R-SALM3C4D',
    status: 'active',
    chips: [
      { labelKey: 'members.chips.weapon', valueKey: 'members.weapons.all' },
      { labelKey: 'members.chips.events', value: '24' },
      { labelKey: 'members.chips.category', valueKey: 'create.options.refereeCategory.c' },
      { labelKey: 'members.chips.entity', valueKey: 'create.options.entity.civilian' },
    ],
    overview: refereeOverview(
      'members.people.salemGhamdi',
      'members.values.categoryC',
      'members.weapons.allWeapons',
      'create.options.entity.civilian',
    ),
    sanctions: [],
  },
  {
    id: 'referee-salem-4',
    category: 'referee',
    nameKey: 'members.people.salemGhamdi',
    photoIndex: 4,
    federationId: 'SFF-R-SALM4D5E',
    status: 'active',
    chips: [
      { labelKey: 'members.chips.weapon', valueKey: 'members.weapons.all' },
      { labelKey: 'members.chips.events', value: '24' },
      { labelKey: 'members.chips.category', valueKey: 'create.options.refereeCategory.a' },
      { labelKey: 'members.chips.entity', valueKey: 'create.options.entity.civilian' },
    ],
    overview: refereeOverview(
      'members.people.salemGhamdi',
      'members.values.categoryA',
      'members.weapons.allWeapons',
      'create.options.entity.civilian',
    ),
    sanctions: [],
  },
  {
    id: 'referee-salem-5',
    category: 'referee',
    nameKey: 'members.people.salemGhamdi',
    photoIndex: 5,
    federationId: 'SFF-R-SALM5E6F',
    status: 'active',
    chips: [
      { labelKey: 'members.chips.weapon', valueKey: 'members.weapons.sabre' },
      { labelKey: 'members.chips.events', value: '24' },
      { labelKey: 'members.chips.category', valueKey: 'create.options.refereeCategory.b' },
      { labelKey: 'members.chips.entity', valueKey: 'create.options.entity.military' },
    ],
    overview: refereeOverview(
      'members.people.salemGhamdi',
      'members.values.categoryB',
      'members.weapons.sabre',
      'create.options.entity.military',
    ),
    sanctions: [],
  },
  {
    id: 'referee-salem-6',
    category: 'referee',
    nameKey: 'members.people.salemGhamdi',
    photoIndex: 6,
    federationId: 'SFF-R-SALM6F7G',
    status: 'active',
    chips: [
      { labelKey: 'members.chips.weapon', valueKey: 'members.weapons.all' },
      { labelKey: 'members.chips.events', value: '24' },
      { labelKey: 'members.chips.category', valueKey: 'create.options.refereeCategory.a' },
      { labelKey: 'members.chips.entity', valueKey: 'create.options.entity.civilian' },
    ],
    overview: refereeOverview(
      'members.people.salemGhamdi',
      'members.values.categoryA',
      'members.weapons.allWeapons',
      'create.options.entity.civilian',
    ),
    sanctions: [],
  },
];

const ADMINS: AdministratorMember[] = [
  {
    id: 'admin-waleed',
    category: 'administrator',
    nameKey: 'members.people.waleedAhmadi',
    photoIndex: 1,
    federationId: 'SFF-D-WALE1A2B',
    status: 'active',
    phone: '+966 55 222 3344',
    email: 'waleed@rfa.sa',
    chips: [
      { labelKey: 'members.chips.department', valueKey: 'members.departments.medical' },
      { labelKey: 'members.chips.role', valueKey: 'members.roles.teamDoctor' },
      { labelKey: 'members.chips.club', valueKey: 'members.clubs.hilal' },
    ],
    overview: [],
    sanctions: [],
  },
  {
    id: 'admin-noura',
    category: 'administrator',
    nameKey: 'members.people.nouraQahtani',
    photoIndex: 2,
    federationId: 'SFF-D-NOUR2B3C',
    status: 'onLeave',
    phone: '+966 55 222 3344',
    email: 'noura@rfa.sa',
    chips: [
      { labelKey: 'members.chips.department', valueKey: 'members.departments.medical' },
      { labelKey: 'members.chips.role', valueKey: 'members.roles.nutritionist' },
      { labelKey: 'members.chips.club', valueKey: 'members.clubs.makkah' },
    ],
    overview: [],
    sanctions: [],
  },
  {
    id: 'admin-waleed-2',
    category: 'administrator',
    nameKey: 'members.people.waleedAhmadi',
    photoIndex: 3,
    federationId: 'SFF-D-WALE3C4D',
    status: 'active',
    phone: '+966 55 222 3344',
    email: 'waleed@rfa.sa',
    chips: [
      { labelKey: 'members.chips.department', valueKey: 'members.departments.medical' },
      { labelKey: 'members.chips.role', valueKey: 'members.roles.teamDoctor' },
      { labelKey: 'members.chips.club', valueKey: 'members.clubs.jeddah' },
    ],
    overview: [],
    sanctions: [],
  },
  {
    id: 'admin-noura-2',
    category: 'administrator',
    nameKey: 'members.people.nouraQahtani',
    photoIndex: 4,
    federationId: 'SFF-D-NOUR4D5E',
    status: 'onLeave',
    phone: '+966 55 222 3344',
    email: 'noura@rfa.sa',
    chips: [
      { labelKey: 'members.chips.department', valueKey: 'members.departments.medical' },
      { labelKey: 'members.chips.role', valueKey: 'members.roles.nutritionist' },
      { labelKey: 'members.chips.club', valueKey: 'members.clubs.makkah' },
    ],
    overview: [],
    sanctions: [],
  },
  {
    id: 'admin-waleed-3',
    category: 'administrator',
    nameKey: 'members.people.waleedAhmadi',
    photoIndex: 5,
    federationId: 'SFF-D-WALE5E6F',
    status: 'active',
    phone: '+966 55 222 3344',
    email: 'waleed@rfa.sa',
    chips: [
      { labelKey: 'members.chips.department', valueKey: 'members.departments.medical' },
      { labelKey: 'members.chips.role', valueKey: 'members.roles.teamDoctor' },
      { labelKey: 'members.chips.club', valueKey: 'members.clubs.hilal' },
    ],
    overview: [],
    sanctions: [],
  },
];

export const DUMMY_MEMBERS_STATE: MembersState = {
  items: [...PLAYERS, ...COACHES, ...REFEREES, ...ADMINS],
  totalCount: 264,
  suspendedCount: 30,
};
