import type { BrowseClub, ClubRegionFilter } from '../types';

export const CLUB_REGION_FILTERS: ClubRegionFilter[] = [
  'all',
  'riyadh',
  'jeddah',
  'dammam',
];

export const BROWSE_CLUBS: BrowseClub[] = [
  {
    id: 'club-hilal',
    nameKey: 'create.options.club.hilal',
    logoId: 'hilal',
    federationId: 'SFF-C-HILAL01',
    region: 'riyadh',
    category: 'premier',
    playerCount: 28,
    playerIds: [
      'player-abdullah',
      'player-hana',
      'player-faisal-1',
      'player-faisal-2',
      'player-faisal-3',
      'player-faisal-4',
    ],
  },
  {
    id: 'club-nassr',
    nameKey: 'create.options.club.nassr',
    logoId: 'nassr',
    federationId: 'SFF-C-NASSR02',
    region: 'riyadh',
    category: 'premier',
    playerCount: 24,
    playerIds: ['player-abdullah', 'player-faisal-1', 'player-faisal-2'],
  },
  {
    id: 'club-ahli',
    nameKey: 'create.options.club.ahli',
    logoId: 'ahli',
    federationId: 'SFF-A-XCFR7ZBW',
    region: 'riyadh',
    category: 'standard',
    playerCount: 22,
    playerIds: [
      'player-abdullah',
      'player-hana',
      'player-faisal-1',
      'player-faisal-2',
      'player-faisal-3',
      'player-faisal-4',
    ],
  },
  {
    id: 'club-shabab',
    nameKey: 'create.options.club.shabab',
    logoId: 'shabab',
    federationId: 'SFF-C-SHAB03',
    region: 'riyadh',
    category: 'premier',
    playerCount: 19,
    playerIds: ['player-faisal-1', 'player-faisal-2', 'player-faisal-3'],
  },
  {
    id: 'club-fayha',
    nameKey: 'create.options.club.fayha',
    logoId: 'fayha',
    federationId: 'SFF-C-FAYH04',
    region: 'riyadh',
    category: 'standard',
    playerCount: 16,
    playerIds: ['player-hana', 'player-faisal-4'],
  },
  {
    id: 'club-wehda',
    nameKey: 'create.options.club.wehda',
    logoId: 'wehda',
    federationId: 'SFF-C-WEHD05',
    region: 'jeddah',
    category: 'standard',
    playerCount: 18,
    playerIds: ['player-abdullah', 'player-faisal-1'],
  },
  {
    id: 'club-faisaly',
    nameKey: 'create.options.club.faisaly',
    logoId: 'faisaly',
    federationId: 'SFF-C-FAIS06',
    region: 'riyadh',
    category: 'standard',
    playerCount: 15,
    playerIds: ['player-faisal-2', 'player-faisal-3'],
  },
  {
    id: 'club-abha',
    nameKey: 'create.options.club.abha',
    logoId: 'abha',
    federationId: 'SFF-C-ABHA07',
    region: 'dammam',
    category: 'standard',
    playerCount: 14,
    playerIds: ['player-hana', 'player-faisal-4'],
  },
  {
    id: 'club-ittihad',
    nameKey: 'create.options.club.ittihad',
    logoId: 'ittihad',
    federationId: 'SFF-C-ITTI08',
    region: 'jeddah',
    category: 'premier',
    playerCount: 26,
    playerIds: [
      'player-abdullah',
      'player-hana',
      'player-faisal-1',
      'player-faisal-2',
    ],
  },
];

export function getBrowseClubById(id: string): BrowseClub | undefined {
  return BROWSE_CLUBS.find((club) => club.id === id);
}
