import type { FederationState } from '../types';

export const DUMMY_FEDERATION_STATE: FederationState = {
  clubs: [
    {
      id: 'club-ittihad',
      nameKey: 'create.options.club.ittihad',
      name: '',
      region: 'jeddah',
      category: 'premier',
      playerCount: '48',
    },
    {
      id: 'club-riyadh',
      nameKey: 'create.options.club.riyadh',
      name: '',
      region: 'riyadh',
      category: 'premier',
      playerCount: '36',
    },
    {
      id: 'club-hilal',
      nameKey: 'create.options.club.hilal',
      name: '',
      region: 'riyadh',
      category: 'standard',
      playerCount: '29',
    },
  ],
  punishments: [
    {
      id: 'punishment-1',
      offenderType: 'player',
      name: 'Hana Rashed',
      penaltyType: 'warning',
      reason: 'Late arrival',
      startDate: '2026-08-10',
      endDate: '2026-08-17',
      issuedBy: 'federation',
    },
    {
      id: 'punishment-2',
      offenderType: 'coach',
      name: 'Ibrahim Sayed',
      penaltyType: 'suspension',
      reason: 'Fair play violation',
      startDate: '2026-08-01',
      endDate: '2026-08-31',
      issuedBy: 'federation',
    },
  ],
  rankings: [
    {
      id: 'rank-1',
      rank: 1,
      nameKey: 'competitions.people.abdullahFaisal',
      clubKey: 'create.options.club.ittihad',
      points: 1840,
    },
    {
      id: 'rank-2',
      rank: 2,
      nameKey: 'competitions.people.faisalQahtani',
      clubKey: 'create.options.club.riyadh',
      points: 1684,
    },
    {
      id: 'rank-3',
      rank: 3,
      nameKey: 'competitions.people.saadDosari',
      clubKey: 'create.options.club.hilal',
      points: 1510,
    },
    {
      id: 'rank-4',
      rank: 4,
      nameKey: 'competitions.people.hanaRashed',
      clubKey: 'create.options.club.ittihad',
      points: 1365,
    },
  ],
  results: [
    {
      id: 'result-1',
      competitionKey: 'competitions.items.asian.name',
      dateKey: 'competitions.items.asian.date',
      winnerKey: 'competitions.people.abdullahFaisal',
      score: '15-11',
    },
    {
      id: 'result-2',
      competitionKey: 'competitions.items.worldCup.name',
      dateKey: 'competitions.shared.august25',
      winnerKey: 'competitions.people.faisalQahtani',
      score: '15-9',
    },
    {
      id: 'result-3',
      competitionKey: 'home.banner.youth.title',
      dateKey: 'home.banner.youth.date',
      winnerKey: 'competitions.people.hanaRashed',
      score: '15-13',
    },
  ],
  transfers: [
    {
      id: 'transfer-1',
      playerKey: 'competitions.people.hanaRashed',
      fromClubKey: 'create.options.club.riyadh',
      toClubKey: 'create.options.club.hilal',
      status: 'pending',
      dateKey: 'competitions.shared.august25',
    },
    {
      id: 'transfer-2',
      playerKey: 'competitions.people.saadDosari',
      fromClubKey: 'create.options.club.ittihad',
      toClubKey: 'create.options.club.riyadh',
      status: 'approved',
      dateKey: 'home.banner.kingdom.date',
    },
    {
      id: 'transfer-3',
      playerKey: 'competitions.people.aliMalki',
      fromClubKey: 'create.options.club.hilal',
      toClubKey: 'create.options.club.ittihad',
      status: 'rejected',
      dateKey: 'home.banner.clubs.date',
    },
  ],
};
